### ISSUE TITLE
Improve loading the model

### ISSUE THREAD

**Issue by Huguet57** [huggingface/ratchet#113]
<img width="995" alt="Captura de pantalla 2024-03-05 a les 0 01 34" src="https://github.com/FL33TW00D/ratchet/assets/6130834/bf5ae27c-7f47-4a6a-8702-8b6342e1e1aa">

Loading the large v2 model from DB (so no fetching involved) lasts almost a minute while paralyzing everything else (can't click on anything), maybe blocking the main thread.

If it exists, we should find the way to load the model such that it does not paralyze the page like that.

**Comment by FL33TW00D** [comment]
Thanks for raising this @Huguet57, i'll need to add some benchmarks on loading.

**Comment by FL33TW00D** [comment]
This has changed massively since this issue, closing. Feel free to reopen.
