### ISSUE TITLE
Subgroups 🏎️

### ISSUE THREAD

**Issue by FL33TW00D** [huggingface/ratchet#167]
Looks like subgroups are going to land imminently on `wgpu` as per here: https://github.com/gfx-rs/wgpu/pull/5301

Integrating these should be fun. Few thoughts on what should be done here:
1. We need some kind of `native` vs `web` feature flag, since subgroups haven't shipped on web yet.
2. We need to identify which kernels can benefit (hint. anything with a reduction)
3. Write up some benchmarks on https://github.com/FL33TW00D/wgpu-bench

References:
https://fleetwood.dev/posts/layernorm-as-fast-as-possible
https://github.com/FL33TW00D/wgpu-bench/blob/master/kernels/layernorm/welford_vec4.wgsl#L47

**Comment by AmineDiro** [comment]
In addition to reduce ops, Subgroups can also be useful for warp aware compute like [warptiling](https://siboehm.com/articles/22/CUDA-MMM)

**Comment by FL33TW00D** [comment]
> In addition to reduce ops, Subgroups can also be useful for warp aware compute like [warptiling](https://siboehm.com/articles/22/CUDA-MMM)

Yeah I think the reduction would do nicely in the new GEMV kernels 🔥

**Comment by FL33TW00D** [comment]
Completed in #220
