### ISSUE TITLE
[Q&A] Ratchet vs Candle

### ISSUE THREAD

**Issue by DavidGOrtega** [huggingface/ratchet#168]
@FL33TW00D I know ratchet prior to be a HF project (congrats to you for joining 🤗 !!!) however the question that I have is how this project relates to Candle. To me, they have pretty common objectives.

**Comment by FL33TW00D** [comment]
Hi @DavidGOrtega,
There are a few key differences between Candle & Ratchet:
1. We are focused entirely on inference with WebGPU, and as they say _"through specialisation comes efficiency"_.
2. Huge focus on being cross platform. If we don't run with GPU acceleration out of the box on Windows, MacOS and Linux, that's a bug. I think right now we are one of the only frameworks with DirectX support, for speedy inference on Windows.
3. We don't want to just run the model for you. We want to build a toolkit that makes building web applications with AI integrated really easy. This means managing model caching, auto fetching from the hub, versioning, providing tooling for audio & video etc. etc.
4. We have **0 support for training**, unlike Candle, which allows us to make some optimisations that aren't currently done in Candle.

More than the above, we wanted to explore a different part of the design space, which can be easier separately. We are hoping one day to merge the best ideas from Candle & Ratchet 🤝. There are tons of places where Candle vastly surpasses us.
