### ISSUE TITLE
Ratbot 🐀

### ISSUE THREAD

**Issue by FL33TW00D** [huggingface/ratchet#198]
Ratbot seems to be broken! 
https://github.com/huggingface/ratchet/blob/master/.github/workflows/ratbot.yml

**Comment by EricLBuehler** [comment]
Looks like iryanbell/scc-docker-action was deleted?

**Comment by FL33TW00D** [comment]
> Looks like iryanbell/scc-docker-action was deleted?

Seems like it, it wasn't perfect anyway.
A good code metrics solution would be great :)

**Comment by officialcjunior** [comment]
> @officialcjunior This looks great! If we can comment this on every PR purely for `crates/ratchet-core` that would be perfect.

Awesome. I've done just that on the PR I've opened.

But it appears that we can't really test if it works unless it's merged? I expected the flow on my branch to be triggered on the PR, but it's still the old one.
