### ISSUE TITLE
Ability to load files from Custom URL

### ISSUE THREAD

**Issue by obenjiro** [huggingface/ratchet#208]
I need to deploy rachet to my own personal server, but i have very strict CSP, so i need to move all possible assets to my own server. All webassebmly files and models weights

Currently I can customise init function
```
 await init('MY_HOST_URL_TO_WASM')
```

But I do fail to load model wights form custom location.

ApiBuilder do have `from_custom` method, so I can load model weights from custom location. But the problem is that `Model` class have only `load` method that currently only works with HuggingFace domain, I can not use loaded file and pass it anywhere :/

**Comment by FL33TW00D** [comment]
@obenjiro 
Agree this would be useful, I'd welcome a PR doing this! If not, I can get around to it at some point

**Comment by obenjiro** [comment]
@FL33TW00D made a PR. Plz look at it

**Comment by FL33TW00D** [comment]
Thanks @obenjiro!!
