### ISSUE TITLE
Unable to run model disutil_large_v3 in the example Whisper + Ratchet

### ISSUE THREAD

**Issue by ocavue** [huggingface/ratchet#223]
I tried to run `examples/ratchet-whisper` locally (but change the version of `@ratchet-ml/ratchet-web` to the latest `0.4.0`). The example works fine for model `tiny` but it throws the following error for model `distil_large_v3`. 

```
panicked at /Users/fleetwood/Code/ratchet/crates/ratchet-models/src/whisper/model.rs:73:14:
called `Result::unwrap()` on an `Err` value: JsValue(Error: Failed to fetch resource
Error: Failed to fetch resource
    at imports.wbg.__wbindgen_error_new (
```

<img width="1295" alt="image" src="https://github.com/huggingface/ratchet/assets/24715727/ff5208dc-3528-49d7-92a6-273d868b0c54">

**Comment by FL33TW00D** [comment]
@ocavue oops! Small mistake when moving some files around for the `0.5.0` release, I've just added it back! https://huggingface.co/FL33TW00D-HF/distil-whisper-large-v3/tree/main

**Comment by ocavue** [comment]
It works now. Thanks!
