### ISSUE TITLE
Tensor printer

### ISSUE THREAD

**Issue by FL33TW00D** [huggingface/ratchet#37]
We should correctly print tensors as numpy / pytorch does.
Something like this: https://pytorch.org/docs/master/generated/torch.set_printoptions.html#torch.set_printoptions

**Comment by officialcjunior** [comment]
Hello.

I was looking into getting this done and wanted to get more clarity on how to implement this. I'm sure over a long time, I may get the answers myself, but I thought I'll ask in the meantime:

What all settings do we need and do you think a simple `std::fmt::Display` would do? pytorch seems to have [a class](https://github.com/pytorch/pytorch/blob/main/torch/_tensor_str.py#L121) for helping format different kinds of tensors.

What I thought of was:
- Make `struct PrintOptions`with the options inside and impl the setter methods.
- Take a reference of `PrintOptions` to `impl fmt::Display for Tensor`
- Find out all the options and send it to another function, maybe in `impl Tensor`, to do the actual printing?

Can you briefly describe the architectural flow you have in mind about this?

I've worked with Rust a long ago. I've lost a few bits, but with a little nudge, I might be able to do this :)

(Great project, btw - looking forward to contribute more)

**Comment by FL33TW00D** [comment]
Hey @officialcjunior!

To be honest with you this issue isn't super pressing right now, given that we have fluid interop with `ndarray`, which does have a tensor printer.

If you do want to tackle it, then I think the `ndarray` example basically just needs to be ported across! https://github.com/rust-ndarray/ndarray/blob/f5d17e5b080233165abdba2e0a4ddf5e2d3d40fc/src/arrayformat.rs#L516

Thanks for the interest! Join the discord if you want to discuss more: https://discord.gg/XFe33KQTG4

**Comment by FL33TW00D** [comment]
Low priority (since we can lean on ndarray), closing for now
