### ISSUE TITLE
Q4 deep dive

### ISSUE THREAD

**Issue by FL33TW00D** [huggingface/ratchet#38]
We need fast (& high quality) 4 bit quantisation.

You can see the kernel I have written here: https://github.com/FL33TW00D/wgpu-mm/blob/master/shaders/qgemm/qgemm_int4.wgsl

This is very naive, and also very slow.

**Comment by sigma-andex** [comment]
References for Q4K:
- https://github.com/ggerganov/llama.cpp/issues/1240
- https://github.com/ggerganov/ggml/blob/cf1acc512432a969cee18947330fd26df67fb456/src/ggml-metal.metal#L5066-L5098
