### ISSUE TITLE
Add feature flag to enable python tests

### ISSUE THREAD

**Issue by sigma-andex** [huggingface/ratchet#85]
Pyo3 doesn't work out of the box, so additional, platform-dependent setup is required. That makes running `cargo test` fail. 

So I think it would be a good idea to enable pyo3 deps, building & testing only when a feature flag is explicitly set, so that `cargo test` works out of the box.

**Comment by FL33TW00D** [comment]
@sigma-andex We had this previously, I removed it since pretty much all of the local tests rely on PyO3.

**Comment by Huguet57** [comment]
> Pyo3 doesn't work out of the box, so additional, platform-dependent setup is required. That makes running `cargo test` fail.
> 
> So I think it would be a good idea to enable pyo3 deps, building & testing only when a feature flag is explicitly set, so that `cargo test` works out of the box.

I was just having this problem right now. Lots of problems with the python tests:

```
dyld[34967]: Library not loaded: @rpath/Python3.framework/Versions/3.9/Python3
  Referenced from: <F4F2ADAF-2EDE-3489-B237-F471AA43D3E6> /Users/andreu/Documents/ratchet/ratchet/target/debug/deps/ratchet-a842f29dc7a9db78
  Reason: tried: '/Library/Frameworks/Python3.framework/Versions/3.9/Python3' (not a file), '/System/Library/Frameworks/Python3.framework/Versions/3.9/Python3' (no such file, not in dyld cache)
```

**Comment by FL33TW00D** [comment]
> > Pyo3 doesn't work out of the box, so additional, platform-dependent setup is required. That makes running `cargo test` fail.
> > So I think it would be a good idea to enable pyo3 deps, building & testing only when a feature flag is explicitly set, so that `cargo test` works out of the box.
> 
> I was just having this problem right now. Lots of problems with the python tests:
> 
> ```
> dyld[34967]: Library not loaded: @rpath/Python3.framework/Versions/3.9/Python3
>   Referenced from: <F4F2ADAF-2EDE-3489-B237-F471AA43D3E6> /Users/andreu/Documents/ratchet/ratchet/target/debug/deps/ratchet-a842f29dc7a9db78
>   Reason: tried: '/Library/Frameworks/Python3.framework/Versions/3.9/Python3' (not a file), '/System/Library/Frameworks/Python3.framework/Versions/3.9/Python3' (no such file, not in dyld cache)
> ```

Hi @Huguet57,
Have you run `just install-pyo3` in the `ratchet` directory? Pyo3 requires pyenv & a static installation of python to work.

**Comment by Huguet57** [comment]
Now I did. Still different errors appear: `Undefined symbols for architecture arm64` (I am using MacOS with the M1 chip). Maybe a README with a couple of instructions on how to test and on which platforms it is supported (I am guessing Linux, now) would help.

**Comment by Huguet57** [comment]
Update: I was able to run the tests successfully after a long battle. :) Maybe I will do a pull request to add to the README.md the instructions for running the tests.

**Comment by FL33TW00D** [comment]
Nice job @Huguet57, please add a comment or raise a PR detailing the issues you faced

**Comment by sigma-andex** [comment]
> @sigma-andex We had this previously, I removed it since pretty much all of the local tests rely on PyO3.

@FL33TW00D true, but I guess this is gonna change in the future. E.g. gguf / quantisation, hub loading, wasm-tests will not require pyo3

**Comment by FL33TW00D** [comment]
Completed
